baseURL = "//2001y.me"
languageCode = "jp"
title = "2001Y.me"
theme = "2001Y.me"
googleAnalytics = "UA-68964193-14"
disqusShortname= "2001y-me"
# enableRobotsTXT = true
# UglyURLs = true
hasCJKLanguage = true
enableGitInfo = true
Paginate = 10
pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsStyle = "monokai"

[author]
  author = "2001Y"
  profile = "自己紹介"
  image = "path/to/profile/image.png"

[params]
  localeOgp = "ja"
  description = "トップページ用の説明文"
  fbAppId = "facebookのAppIDを入れる"
  ogpimage = "images/ogp.png"
  ogpimagewidth = "1200"
  opgimageheight = "620"
  twitter = "twitterCard用のユーザー名を入れる"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]