[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.53.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --minify"

[context.split1.environment]
HUGO_VERSION = "0.53.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --minify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.53.0"

[context.branch-deploy]
command = "hugo --minify

[context.branch-deploy.environment]
HUGO_VERSION = "0.53.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
